# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter waffle,$(TARGET_DEVICE)),)

endif
